### PR TITLE
Move to new ruby / rails version

### PR DESCRIPTION
**Pull request by nikolai-b**
Add things we need to do here:

The vendor plugins are very old and the format of keeping 
them in a vendor dir is depricated.
rails-authorization-plugin
is a pain because it hasn't been worked on in years,
can we switch to using devise? Not sure if that would make 
existing users lose their passwords.

In the newer versions of rails the initialization / boot process
has changed.  We need to migrate the config files to the new format.

### CODE REVIEW

**Comment by nikolai-b** [comment]
@dan-mi-sun I think we should be working on this branch and when it's ready get it merged into master.  Have you managed to get this version of ruby working?

**Comment by nikolai-b** [comment]
@dan-mi-sun I've made some progress on this.  Can you try `bundle exec rake test` to see you are also getting "1 failures, 4 errors" on the first batch and "6 failures" on the second.

**Comment by ghost** [comment]
Not that easy to decipher what is going on. Assuming I am needing to  sudo systemctl start mysqld.service before running the test....

This is the end output: 111 tests, 46 assertions, 0 failures, 88 errors, 0 skips

**Comment by ghost** [comment]
Did you want me to merge a branch also? Sorry, still getting used to the workflow of git.

**Comment by ghost** [comment]
We can’t automatically merge this pull request.
Use the command line to resolve conflicts before continuing.

This is what github is telling me^

**Comment by nikolai-b** [comment]
88 errors?  That more than me.  Have you done a `git pull` and `git checkout bump-ruby` to get the latest stuff?  Not ready to merge yet but we can deal with that tomorrow.

**Pull request closed without merging**
